(()=>{
function waitForApp(){let n=0,t=setInterval(()=>{n++;if(document.getElementById('files')&&document.getElementById('result')&&document.getElementById('gallery')){clearInterval(t);init()}else if(n>80)clearInterval(t)},100)}
function init(){
 const $=id=>document.getElementById(id), V=id=>($(id)?.value||'').trim(), N=x=>{let n=Number(String(x||'').replace(/[,，¥￥%\s]/g,''));return Number.isFinite(n)?n:NaN};
 const fileInput=$('files'), dropPanel=document.querySelector('.dropPanel'), previewPanel=$('previewPanel');
 let sourceItems=[], autoPickKey='';
 const sourcePanel=document.createElement('section');sourcePanel.className='panel v5-sources';sourcePanel.innerHTML='<div class="v5-head"><div><b>我收到了这些资料</b> <span>系统会自动判断用途</span></div><span id="v5SourceCount">0 项</span></div><div id="v5SourceGrid" class="v5-source-grid"><div class="v5-empty">上传后会在这里告诉你：哪些是文档、哪些是资料截图、哪些是活动照片。</div></div>';
 dropPanel.insertAdjacentElement('afterend',sourcePanel);
 const quality=document.createElement('section');quality.className='panel v5-quality hidden';quality.innerHTML='<div class="v5-quality-box"><div class="v5-quality-top"><div class="v5-ring" id="v5Ring"><b id="v5Score">0%</b></div><div class="v5-quality-copy"><b id="v5Title">生成前检查</b><span id="v5Desc">我会检查关键数据、照片、大单排行和信息冲突。</span></div><button class="v5-check" id="v5Check">一键检查</button></div><div class="v5-checks"><div class="v5-check-item" id="v5Key"><small>关键资料</small><b>待检查</b></div><div class="v5-check-item" id="v5Top"><small>大单排行</small><b>待检查</b></div><div class="v5-check-item" id="v5Photo"><small>活动照片</small><b>待检查</b></div><div class="v5-check-item" id="v5Conflict"><small>信息冲突</small><b>待检查</b></div></div><div id="v5Alert" class="v5-alert"></div><div id="v5PhotoHint" class="v5-photo-hint"></div><div class="v5-toolbar"><button id="v5AutoPhoto">自动挑最好照片</button><button id="v5FocusMissing">只看缺失项</button><button id="v5CopySummary">复制老板摘要</button></div></div>';
 if(previewPanel)previewPanel.insertAdjacentElement('beforebegin',quality);else document.querySelector('.result')?.insertAdjacentElement('afterend',quality);
 function extType(f){let e=f.name.split('.').pop().toLowerCase();if(f.type.startsWith('image/'))return'IMG';if(e==='xlsx')return'XLS';if(e==='docx')return'DOC';if(e==='pdf')return'PDF';if(e==='csv')return'CSV';return'TXT'}
 function addSources(fs,fromPaste=false){for(const f of fs){sourceItems.push({name:f.name||('粘贴图片 '+(sourceItems.length+1)),type:extType(f),kind:f.type.startsWith('image/')?'识别中':'文档资料',status:'正在分析',confidence:'mid',paste:fromPaste})}renderSources();setTimeout(classifySources,2600)}
 function renderSources(){let g=$('v5SourceGrid');$('v5SourceCount').textContent=sourceItems.length+' 项';if(!sourceItems.length){g.innerHTML='<div class="v5-empty">上传后会在这里告诉你：哪些是文档、哪些是资料截图、哪些是活动照片。</div>';return}g.innerHTML=sourceItems.map(x=>`<div class="v5-source"><div class="v5-source-icon">${x.type}</div><div class="v5-source-main"><b title="${escapeHtml(x.name)}">${escapeHtml(x.name)}</b><small>${x.kind}</small></div><span class="v5-badge ${x.confidence==='ok'?'ok':x.confidence==='mid'?'mid':''}">${x.status}</span></div>`).join('')}
 function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function classifySources(){let photoNames=[...document.querySelectorAll('#gallery img')].map(i=>i.title||'');sourceItems=sourceItems.map(x=>{if(x.type==='IMG'){let photo=photoNames.includes(x.name);return{...x,kind:photo?'活动照片':'资料截图',status:photo?'已用于选图':'已提取文字',confidence:'ok'}}return{...x,status:'已读取',confidence:'ok'}});renderSources();updateQuality();if(photoNames.length>3)autoPickPhotos(true)}
 fileInput.addEventListener('change',e=>addSources([...e.target.files]),true);
 document.addEventListener('paste',e=>{let fs=[...(e.clipboardData?.files||[])].filter(f=>f.type.startsWith('image/'));if(fs.length)addSources(fs,true)},true);
 const fileMsg=$('filemsg');if(fileMsg){new MutationObserver(()=>{if(/整理完成/.test(fileMsg.textContent)){classifySources();setTimeout(updateQuality,300)}}).observe(fileMsg,{childList:true,subtree:true,characterData:true})}
 function keyStats(){let defs=[['event','活动名称'],['date','日期'],['loc','地点'],['revenue','成交额'],['arrivals','到场人数'],['deals','成交笔数']],missing=defs.filter(([id])=>!V(id));return{defs,missing,done:defs.length-missing.length}}
 function topStats(){let ok=0;for(let i=1;i<=3;i++)if(V('n'+i)&&Number.isFinite(N(V('a'+i))))ok++;return ok}
 function photoStats(){return document.querySelectorAll('#photos .photo').length}
 function conflictStats(){return document.querySelectorAll('.conflict').length}
 function item(id,good,text){let e=$(id);e.className='v5-check-item '+(good?'good':'warn');e.querySelector('b').textContent=text}
 function updateQuality(){if(!document.getElementById('result')||document.getElementById('result').classList.contains('hidden')){quality.classList.add('hidden');return}quality.classList.remove('hidden');let k=keyStats(),top=topStats(),ph=photoStats(),cf=conflictStats(),score=Math.round((k.done/k.defs.length)*60+(Math.min(top,3)/3)*15+(Math.min(ph,3)/3)*15+(cf?0:10));$('v5Ring').style.setProperty('--v5-score',score+'%');$('v5Score').textContent=score+'%';item('v5Key',!k.missing.length,k.missing.length?'缺 '+k.missing.length+' 项':'已完整');item('v5Top',top>=3,top>=3?'TOP3 完整':top+' / 3');item('v5Photo',ph>=3,ph>=3?'3 张已选':ph+' / 3');item('v5Conflict',cf===0,cf?cf+' 处待确认':'无冲突');let warnings=[];if(k.missing.length)warnings.push('还缺：'+k.missing.map(x=>x[1]).join('、'));if(cf)warnings.push('存在信息冲突，请在“高级修改”里确认');if(ph<3)warnings.push('活动照片不足 3 张，PPT 会出现占位图');let alert=$('v5Alert');alert.classList.toggle('show',warnings.length>0);alert.textContent=warnings.join(' ｜ ');$('v5Title').textContent=score>=90?'✓ 已达到直接汇报状态':score>=70?'基本可以生成，建议再检查一下':'建议先补齐关键资料';$('v5Desc').textContent=score>=90?'关键数据、照片和成交结构都已准备好。':'我会继续根据你补充的资料实时检查。'}
 ['event','date','loc','revenue','arrivals','deals','n1','a1','n2','a2','n3','a3'].forEach(id=>$(id)?.addEventListener('input',()=>setTimeout(updateQuality,0)));
 new MutationObserver(()=>updateQuality()).observe($('photos'),{childList:true,subtree:true});
 new MutationObserver(()=>updateQuality()).observe($('conflicts'),{childList:true,subtree:true});
 $('v5Check').onclick=()=>{updateQuality();quality.scrollIntoView({behavior:'smooth',block:'center'})};
 $('v5FocusMissing').onclick=()=>{let m=keyStats().missing;if(!m.length){$('v5Alert').classList.add('show');$('v5Alert').textContent='✓ 关键资料已经齐了。';return}document.querySelector('.advanced')?.setAttribute('open','');let el=$(m[0][0]);el?.focus();el?.scrollIntoView({behavior:'smooth',block:'center'})};
 $('v5CopySummary').onclick=async()=>{let t=[V('summary'),V('management')].filter(Boolean).join('\n');if(!t)return;try{await navigator.clipboard.writeText(t);$('v5PhotoHint').className='v5-photo-hint show';$('v5PhotoHint').textContent='✓ 老板摘要已复制';setTimeout(()=>$('v5PhotoHint').classList.remove('show'),1800)}catch{}};
 function runCmd(t){let i=$('cmd'),b=$('go');if(!i||!b)return;i.value=t;b.click()}
 function galleryImages(){return[...document.querySelectorAll('#gallery img')].filter(i=>i.naturalWidth&&i.naturalHeight)}
 function qualityScore(img){let px=img.naturalWidth*img.naturalHeight,ar=img.naturalWidth/img.naturalHeight,aspectPenalty=(ar<.38||ar>2.4)?.38:1,res=Math.log10(Math.max(px,1));return res*aspectPenalty}
 function autoPickPhotos(silent=false){let imgs=galleryImages();if(imgs.length<3){if(!silent){$('v5PhotoHint').className='v5-photo-hint show';$('v5PhotoHint').textContent='照片不足 3 张，暂时无法自动挑选。'}return}let key=imgs.map(i=>i.title+':'+i.naturalWidth+'x'+i.naturalHeight).join('|');if(silent&&autoPickKey===key)return;autoPickKey=key;let ranked=imgs.map((img,i)=>({i,score:qualityScore(img),ar:img.naturalWidth/img.naturalHeight})).sort((a,b)=>b.score-a.score).slice(0,Math.min(6,imgs.length));let first=[...ranked].sort((a,b)=>Math.abs(a.ar-1.05)-Math.abs(b.ar-1.05))[0],remain=ranked.filter(x=>x.i!==first.i),third=[...remain].sort((a,b)=>Math.abs(a.ar-.68)-Math.abs(b.ar-.68))[0],second=remain.filter(x=>x.i!==third.i)[0]||remain[0];let picks=[first,second,third].filter(Boolean);let roles=['活动现场','互动过程','手作细节'];picks.forEach((p,slot)=>runCmd(`用第${p.i+1}张照片做${roles[slot]}`));let hint=$('v5PhotoHint');hint.className='v5-photo-hint show';hint.textContent='✓ 已按清晰度和构图自动挑选 3 张照片；不满意可以点“换照片”。';setTimeout(()=>{if(silent)hint.classList.remove('show')},3500);setTimeout(updateQuality,200)}
 $('v5AutoPhoto').onclick=()=>autoPickPhotos(false);
 const gallery=$('gallery');new MutationObserver(()=>{let imgs=galleryImages();if(imgs.length>3)setTimeout(()=>autoPickPhotos(true),300)}).observe(gallery,{childList:true,subtree:true});
 const gen=$('generate');if(gen)gen.addEventListener('click',()=>{updateQuality();let k=keyStats(),cf=conflictStats();if(k.missing.length||cf){$('v5Alert').classList.add('show');$('v5Alert').textContent=(k.missing.length?'生成前提醒：还缺 '+k.missing.map(x=>x[1]).join('、'):'')+(cf?'；还有 '+cf+' 处信息冲突':'')}} ,true);
 const result=$('result');new MutationObserver(()=>updateQuality()).observe(result,{attributes:true,attributeFilter:['class']});
 setTimeout(()=>{classifySources();updateQuality()},1200)
}
waitForApp();
})();