(async()=>{
  const base='https://cdn.jsdelivr.net/gh/wangmiao033/blank-app@f304b251e3e47d7217a58b034ab44ecad82f56d6/awaken-v4/app.js';
  let s=await (await fetch(base,{cache:'force-cache'})).text();
  s=s.replace("function addPhoto(f){pics.push({f,url:URL.createObjectURL(f),name:f.name});sources.photos++;if(pics.length>12){let x=pics.shift();URL.revokeObjectURL(x.url)}selected=selected.map((x,i)=>pics[x]?x:Math.min(i,pics.length-1));renderPhotos()}","function normalizeSelected(){let valid=[];for(let x of selected)if(Number.isInteger(x)&&x>=0&&x<pics.length&&!valid.includes(x))valid.push(x);for(let i=0;i<pics.length&&valid.length<3;i++)if(!valid.includes(i))valid.push(i);selected=valid}\nfunction addPhoto(f){pics.push({f,url:URL.createObjectURL(f),name:f.name});sources.photos++;if(pics.length>12){let x=pics.shift();URL.revokeObjectURL(x.url)}normalizeSelected();renderPhotos()}");
  s=s.replace("function renderQuestion(){let ms=missing(),q=$('question'),row=$('askrow');if(!ms.length)","function renderQuestion(){let ms=missingDefs.slice(0,6).filter(([id])=>!V(id)),q=$('question'),row=$('askrow');if(!ms.length)");
  s=s.replace("pics.splice(remove,1);selected=[0,1,2].map(i=>Math.min(i,Math.max(0,pics.length-1)));sources.photos=Math.max(0,sources.photos-1);renderAll()","pics.splice(remove,1);selected=selected.map(v=>v>remove?v-1:v).filter(v=>v!==remove);normalizeSelected();sources.photos=Math.max(0,sources.photos-1);renderAll()");
  s=s.replace("if(!event){let l=lines.find(x=>x.length>=4&&x.length<45&&/(手作|会员|活动)/.test(x)&&!/(地点|时间|日期|成交|到场|邀约|首页内容|背景)/.test(x));if(l)event=l}let date=get([","if(!event){let l=lines.find(x=>x.length>=4&&x.length<45&&/(手作|会员|活动)/.test(x)&&!/(地点|时间|日期|成交|到场|邀约|首页内容|背景)/.test(x));if(l)event=l}if(!event){let m=t.match(/(?:昨天|今天|上周)?\\s*([^，。\\n]{2,16})(?:做了?|搞了?|举办了?)(?:一场)?([^，。\\n]{2,14}(?:活动|手作))/);if(m)event=(m[1]+m[2]).replace(/\\s+/g,'')}let date=get([");
  s=s.replace("let date=get([/(20\\d{2}[-/.年]\\d{1,2}[-/.月]\\d{1,2})/,/(\\d{1,2}[/.]\\d{1,2})/,/(\\d{1,2}月\\d{1,2}日?)/]),time=get([/(\\d{1,2}:\\d{2}\\s*[–—~-]\\s*\\d{1,2}:\\d{2})/]),loc=get([/(?:活动地点|地点|门店)\\s*[:=]?\\s*([^\\n]+)/]);if(!loc){let l=lines.find(x=>/(店|商场|荟聚|门店|中心)$/.test(x)&&x.length<30);if(l)loc=l.replace(/^活动地点\\s*/,'')}","let date=get([/(20\\d{2}[-/.年]\\d{1,2}[-/.月]\\d{1,2})/,/(\\d{1,2}[/.]\\d{1,2})/,/(\\d{1,2}月\\d{1,2}日?)/]);if(!date&&/昨天/.test(t)){let z=new Date();z.setDate(z.getDate()-1);date=`${z.getFullYear()}-${z.getMonth()+1}-${z.getDate()}`}let time=get([/(\\d{1,2}:\\d{2}\\s*[–—~-]\\s*\\d{1,2}:\\d{2})/]),loc=get([/(?:活动地点|地点|门店)\\s*[:=]?\\s*([^\\n]+)/]);if(!loc){let l=lines.find(x=>/(店|商场|荟聚|门店|中心)$/.test(x)&&x.length<30);if(l)loc=l.replace(/^活动地点\\s*/,'')}if(!loc){let m=t.match(/(?:昨天|今天|上周)?\\s*(?:在)?([^，。\\n]{2,12})(?:做了?|搞了?|举办了?)/);if(m)loc=m[1].trim()}");
  s=s.replace("else if(/重写|重新|生成/.test(t)){autoNarrative(true);done.push('重新生成结论')}}renderAll();","else if(/重写|重新|生成/.test(t)){autoNarrative(true);done.push('重新生成结论')}}let pm=t.match(/第?([一二三四五六七八九十\\d]+)张(?:照片|图)?/),cn={一:1,二:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9,十:10};if(pm){let n=/^\\d+$/.test(pm[1])?+pm[1]:(cn[pm[1]]||0),idx=n-1;if(idx>=0&&idx<pics.length){if(/删除|去掉|不要/.test(t)){let x=pics[idx];URL.revokeObjectURL(x.url);pics.splice(idx,1);selected=selected.map(v=>v>idx?v-1:v).filter(v=>v!==idx);normalizeSelected();sources.photos=Math.max(0,sources.photos-1);done.push('删除第'+n+'张照片')}else{let slot=/活动现场/.test(t)?0:/互动/.test(t)?1:/(手作细节|细节)/.test(t)?2:-1;if(slot>=0){selected[slot]=idx;normalizeSelected();done.push('调整照片')}}}}renderAll();");
  (0,eval)(s+'\n//# sourceURL=awaken-v4-app.js');
})().catch(e=>{console.error(e);document.body.insertAdjacentHTML('afterbegin','<div style="padding:10px;text-align:center;background:#fff1eb;color:#a43f20;font:12px system-ui">核心脚本加载失败，请刷新页面重试。</div>')});